# Generated by Django 5.2.7 on 2025-10-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_comment_postimage_delete_basicpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=100, verbose_name='태그'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='제목없음', max_length=100, verbose_name='제목'),
        ),
        migrations.DeleteModel(
            name='CommentPost',
        ),
    ]
