# Generated by Django 5.2.7 on 2025-10-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='short_description',
            field=models.CharField(blank=True, verbose_name='자기소개글'),
        ),
    ]
