# Generated by Django 5.2.7 on 2025-10-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_post_comment_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
